const apiActions = {
    GET_API_START: 'GET_API_START',
    GET_API_SUCCESS: 'GET_API_SUCCESS',
    GET_API_FAILURE: 'GET_API_FAILURE',
    GET_REGISTERED_USERS: 'GET_REGISTERED_USERS',
    GET_UNREGISTERED_USERS: 'GET_UNREGISTERED_USERS',
    GET_PROJECT_MEMBERSHIPS: 'GET_PROJECT_MEMBERSHIPS',
}

export default apiActions;